### ISSUE TITLE
How to use validators correctly

### ISSUE THREAD

**Issue by ianks** [goatslacker/flux-form#1]
Can you give a quick example of how one might use the validator option? I would be happy to document it as well once I get a better feel for it.

**Comment by goatslacker** [comment]
Yeah this is really lacking some docs right now. Mostly because I'm just feeling out the API and working out the kinks. Let me flesh out what I've currently got and I'd love to hear your thoughts

**Comment by goatslacker** [comment]
Some docs https://github.com/goatslacker/flux-form/commit/b0a31396e82550d57b99fa7c7aeb5655febd60fe
